gui:
  timeFormat: "2006-01-02 15:04:05"
  shortTimeFormat: "15:04:05"
  border: single
  nerdFontsVersion: ""
git:
  pagers:
    - pager: delta --color-only --paging=never
promptToReturnFromSubprocess: false
